'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { apiMessage, apiRequest } from '@/lib/api';
import type { ConversationItem, ConversationMessageItem, ConversationMessages } from '@viecpro/shared';
import './conversation-inbox.css';

type Side='employer'|'seeker';
type ListResult={items:ConversationItem[];hasMore:boolean};
export default function ConversationInbox({side}:{side:Side}){
  const root=side==='employer'?'/employer':'/me';
  const [items,setItems]=useState<ConversationItem[]>([]);const [selected,setSelected]=useState('');const [messages,setMessages]=useState<ConversationMessageItem[]>([]);const [body,setBody]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const bottom=useRef<HTMLDivElement>(null);const tail=useRef<string|null>(null);
  const loadList=useCallback(async()=>{try{const data=await apiRequest<ListResult>(`${root}/conversations?page=1&limit=50`);setItems(data.items);}catch(e){setError(apiMessage(e,'Không tải được danh sách hội thoại.'));}finally{setLoading(false);}},[root]);
  useEffect(()=>{void loadList();const initial=new URLSearchParams(window.location.search).get('id');if(initial)setSelected(initial);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void loadList();},30_000);return()=>window.clearInterval(timer);},[loadList]);
  const messagePath=`${root}/conversations/${encodeURIComponent(selected)}/messages`;
  const refreshMessages=useCallback(async(initial=false)=>{if(!selected||document.visibilityState!=='visible')return;try{const cursor=!initial&&tail.current?`?after=${encodeURIComponent(tail.current)}`:'';const page=await apiRequest<ConversationMessages>(`${root}/conversations/${encodeURIComponent(selected)}/messages${cursor}`);if(initial){setMessages(page.items);tail.current=page.after;}else if(page.items.length){setMessages(prev=>{const seen=new Set(prev.map(m=>m.id));return [...prev,...page.items.filter(m=>!seen.has(m.id))];});tail.current=page.after;}await apiRequest<void>(`${root}/conversations/${encodeURIComponent(selected)}/read`,{method:'POST'});void loadList();}catch(e){setError(apiMessage(e,'Không tải được tin nhắn.'));}},[root,selected,loadList]);
  useEffect(()=>{if(!selected)return;tail.current=null;setMessages([]);void refreshMessages(true);const timer=window.setInterval(()=>void refreshMessages(false),5_000);const onVisibility=()=>{if(document.visibilityState==='visible')void refreshMessages(false);};document.addEventListener('visibilitychange',onVisibility);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',onVisibility);};},[selected,refreshMessages]);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[messages.length]);
  const active=useMemo(()=>items.find(i=>i.id===selected),[items,selected]);
  const send=async(e:React.FormEvent)=>{e.preventDefault();const text=body.trim();if(!text||busy)return;setBusy(true);setError('');try{const message=await apiRequest<ConversationMessageItem>(messagePath,{method:'POST',body:JSON.stringify({body:text})});setMessages(prev=>[...prev,message]);tail.current=btoa(JSON.stringify({at:message.createdAt,id:message.id})).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');setBody('');void loadList();}catch(e){setError(apiMessage(e,'Không gửi được tin nhắn.'));}finally{setBusy(false);}};
  return <main className={`conversation-inbox ${selected?'conversation-inbox--selected':''}`}><aside className="conversation-list"><header><p>Tin nhắn</p><h1>Hội thoại</h1></header>{loading&&<p className="conversation-empty">Đang tải…</p>}{!loading&&items.length===0&&<p className="conversation-empty">Chưa có cuộc trò chuyện.</p>}{items.map(i=><button key={i.id} className={`conversation-preview ${selected===i.id?'is-active':''}`} onClick={()=>{setSelected(i.id);const u=new URL(window.location.href);u.searchParams.set('id',i.id);window.history.replaceState(null,'',u);}}><span className="conversation-avatar">{i.participantName.slice(0,1)}</span><span className="conversation-preview__text"><b>{i.participantName}</b><small>{i.jobTitle}</small><span>{i.lastMessage?.body??'Bắt đầu cuộc trò chuyện'}</span></span>{i.unread>0&&<em>{i.unread}</em>}</button>)}</aside><section className="conversation-thread">{!selected?<div className="conversation-placeholder">Chọn một cuộc trò chuyện để xem tin nhắn.</div>:<><header className="conversation-thread__head"><button className="conversation-back" onClick={()=>setSelected('')}>‹ Danh sách</button><div><b>{active?.participantName??'Cuộc trò chuyện'}</b><small>{active?.jobTitle}</small></div></header><div className="conversation-messages">{messages.map(m=><article key={m.id} className={`conversation-message conversation-message--${m.senderSide===side?'own':'other'}`}><p>{m.body}</p><time>{new Date(m.createdAt).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}</time></article>)}<div ref={bottom}/></div>{error&&<p className="conversation-error" role="alert">{error}</p>}<form className="conversation-compose" onSubmit={send}><textarea value={body} maxLength={2000} rows={2} placeholder="Nhập tin nhắn…" onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send(e as unknown as React.FormEvent);}}}/><button disabled={busy||!body.trim()}>{busy?'Đang gửi…':'Gửi'}</button></form></>}</section></main>;
}
